---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-db-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: growi
    name: db-data
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/growi/db/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-db-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-db-config
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: growi
    name: db-config
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/growi/db/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-config
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-db-config
