apiVersion: v1
kind: ConfigMap
metadata:
  name: es-conf
data:
  elasticsearch.yml: |
    http.host: 0.0.0.0
    
    # for elasticsearch-head
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    
    xpack.security.enabled: false
