---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-es-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: growi
    name: es
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/growi/es
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-es-data
