---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: up-files
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-retain"
  resources:
    requests:
      storage: 10Gi
