apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClass: "nfs-retain"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-config
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClass: "nfs-retain"
