apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-retain"
